spring:
  application:
    name: gateway-carga
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          #placeholder ater configurar meu próprio realm
          issuer-uir: http://localhost:8081/realms/mscourserealm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-zone:
      default-zone: http://jw-progammer:5151551010@localhost:8761/eureka