spring:
  application:
    name: gateway-carga
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-zone:
      default-zone: http://localhost:8761/eureka