spring:
  application:
    name: servidoreureka
  security:
    basic:
      enable: true
    user:
      name: jw-progammer
      password: 5151551010

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false